// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu6cEWtMMIToaxt2ZQwRyjGDFTkUQNigc',
    appId: '1:247403453845:android:13cfc650154bb0b925aa9c',
    messagingSenderId: '247403453845',
    projectId: 'sample-fcm-app-543cd',
    databaseURL: 'https://sample-fcm-app-543cd-default-rtdb.firebaseio.com',
    storageBucket: 'sample-fcm-app-543cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Rl3m39mxZUoxbRcURRbktxipN6w0NoI',
    appId: '1:247403453845:ios:c6775e6654e1a92025aa9c',
    messagingSenderId: '247403453845',
    projectId: 'sample-fcm-app-543cd',
    databaseURL: 'https://sample-fcm-app-543cd-default-rtdb.firebaseio.com',
    storageBucket: 'sample-fcm-app-543cd.firebasestorage.app',
    iosBundleId: 'org.ims.nexusmobile',
  );

}